---


- name: create mysql-5.6 repo file
  copy: src={{ item }} dest=/etc/yum.repos.d/
  with_items:
    - mysql-community-source.repo
    - mysql-community.repo

- name: GPG-KEY check
  copy: src=RPM-GPG-KEY-mysql dest=/etc/pki/rpm-gpg/




