---
#this playbook will install zabbix-agent,and start service.

- name: Copy Zabbix-agent package
  copy: src=zabbix-agent-3.0.6-1.el7.x86_64.rpm dest=/opt/soft/

- name: Install zabbix agent
  shell: yum install /opt/soft/zabbix-agent-3.0.6-1.el7.x86_64.rpm -y
  ignore_errors: True

- name: instead of agent configure file
  template: src=zabbix_agentd.conf.j2 dest=/etc/zabbix/zabbix_agentd.conf
  notify:
    - restart zabbix-agent


