---

- name: Install Nginx
  yum: name=nginx state=present
  notify:
    - restart nginx

- meta: flush_handlers

- name: add cgi
  template: src=default.conf.j2 dest=/etc/nginx/conf.d/default.conf

- name: check nginx configure file
  shell: nginx -t
  register: nginx_config_check

- name: reload nginx
  shell: nginx -s reload
  when: nginx_config_check != 1
  ignore_errors: yes


- name: php test page
  copy: src=info.php dest=/usr/share/nginx/html/index.php

