#!/usr/bin/python

from ansible.module_utils.basic import *
import os

module = AnsibleModule(
	argument_spec = dict(
	    args=dict(required=True)),
	)

args = module.params['args']
os.system('echo {0} > /tmp/appname'.format(args))

result = dict(echo=args)

module.exit_json(**result)
