version: '2'
services:
  create_user:
    image: "registry:2"
    volumes:
        - ./auth/htpasswd:/auth/htpasswd:rw
    entrypoint: htpasswd -Bb  /auth/htpasswd  admin gI2V6jngNttxKWuiT1XA
  registry:
    image: "registry:2"
    container_name: registry
    ports:
      - 5000:5000
    restart: always
    volumes:
      - ./data:/var/lib/registry
      - ./cert:/certs:ro
      - ./auth:/auth:ro
    environment:
      - REGISTRY_AUTH=htpasswd
      - REGISTRY_AUTH_HTPASSWD_REALM=“Registry Realm”
      - REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd
  #    - REGISTRY_HTTP_TLS_CERTIFICATE=
  #    - REGISTRY_HTTP_TLS_KEY=
