---
# update pip end set repo
- name: mkdir .pip
  file: path=~/.pip state=directory owner=root group=root

- name: copy pip.conf
  copy: src=pip.conf dest=~/.pip/pip.conf

- name: update pip
  shell: pip install -U pip

- name: install docker-compose
  pip: name=docker-compose state=forcereinstall

